name: Deploy application to VM
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'

      - name: Perform install, build commands
        run: |
            npm install 
            npm run lint
      - name: Deploy NextJS app to VM Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/tripseek/deployer && npm start
